Typescriptify
goodhood-eu/nebenan-eventproxy pull request #1
Opened 2023-03-29 10:06 UTC by rejas

2023-03-29 12:08 UTC, peterhass commented on src/index.ts
> +  // handler (which is, in most cases, an unexpected behavior). We can prevent this
![image](https://user-images.githubusercontent.com/34499633/228530668-c5953a97-2bc8-4d12-9ade-e12755f84598.png)

2023-03-29 12:32 UTC, peterhass commented on tsconfig.json
> +    "allowJs": true,
false? js is not needed anymore i guess

2023-03-29 12:32 UTC, peterhass commented on src/index.ts
> +interface EventData {
Would rather use `type` here. You only benefit from Interfaces for global types that might be extended like `window`. Whenever you're sure that you're working with a non-extendable type, go for `type`. (Pretty much: Always use `type` until you can't 😀)

2023-03-29 12:35 UTC, peterhass commented on src/index.ts
> +const addListener = (event:string, callback: HandlerFunction) => {
we could mirror the type of `document.addEventListener` here:     
```ts
addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
```

2023-03-29 13:53 UTC, rejas commented on src/index.ts
> +  // handler (which is, in most cases, an unexpected behavior). We can prevent this
???

2023-03-29 13:54 UTC, peterhass commented on src/index.ts
> +  // handler (which is, in most cases, an unexpected behavior). We can prevent this
Behavior -> behaviour

2023-07-05 16:20 UTC, iamuchejude requested changes
Getting there 🛥️

2023-07-05 16:20 UTC, iamuchejude commented on .eslintrc
> +        "airbnb-typescript/base"
We have an eslint preset for TypeScript

2023-07-05 16:20 UTC, iamuchejude commented on src/index.ts
> +  wrapper?: (callback: Function) => Function;
We should avoid anything similar to `any`. `Function` is basically `any` function.

It's practically to tell the structure of `Function` as it's generic, so type-safety is incomplete.

A fix would be to define types to explicitly describe your function.

2023-07-05 16:20 UTC, iamuchejude commented on src/index.ts
> +    wrapper(callback) { return debounce(callback as any, RESIZE_RATE); },
This won't be necessary if the function type is properly described and the other `anys`

2023-11-23 10:08 UTC, closed without merging